import { decryptSecret, encryptSecret } from "../secrets.ts";

export type ConnectorProvider =
  | "woocommerce" | "supabase" | "resend" | "shopify" | "stripe" | "hubspot"
  | "zendesk" | "slack" | "whatsapp" | "calendly" | "notion" | "google_drive"
  | "dropbox" | "zapier" | "make" | "n8n" | "webhook" | "custom_api"
  | "salesforce" | "intercom" | "freshdesk" | "helpscout" | "gorgias" | "zoho_desk"
  | "messenger" | "instagram" | "twilio" | "wordpress";

export type ConnectorCategory = "commerce"|"payments"|"crm"|"support"|"messaging"|"scheduling"|"knowledge"|"automation"|"developer"|"email"|"database"|"cms";
export interface ConnectorField {key:string;label:string;secret?:boolean;required?:boolean;placeholder?:string;type?:"text"|"url"|"textarea"}
export interface ConnectorActionTemplate {
  id:string; name:string; description:string; capability:string;
  method:"GET"|"POST"|"PUT"|"PATCH"|"DELETE"; pathTemplate:string;
  requestSchema:Record<string,unknown>; responseMapping?:Record<string,unknown>; requireConfirmation?:boolean;
  /** Safe for a normal customer-facing assistant to initiate. The server still
   *  requires confirmation for mutations. Omit/false for admin-only actions. */
  customerSafe?: boolean;
  /** Provider-neutral tool name shown to the model. Never exposed to customers. */
  toolName?: string;
}
export interface ConnectorNativeAction {
  id:string; name:string; description:string; capability:string; toolName:string;
  /** Native actions are executed by ZoChat's provider-neutral capability router,
   * not by the generic connector-action HTTP executor. */
  native:true;
}
export interface ConnectorDefinition {
  id: ConnectorProvider;
  name: string;
  category: ConnectorCategory;
  capabilities: string[];
  fields: ConnectorField[];
  sourceKinds?: string[];
  actionTemplates?: ConnectorActionTemplate[];
  nativeActions?: ConnectorNativeAction[];
  docsUrl?: string;
}

const readList=(name:string,path:string,capability="support.read",toolName?:string):ConnectorActionTemplate=>({id:`${name.toLowerCase().replace(/\W+/g,"_")}_list`,name:`List ${name}`,description:`Read ${name.toLowerCase()} from the connected service.`,capability,method:"GET",pathTemplate:path,requestSchema:{type:"object",properties:{}},requireConfirmation:false,customerSafe:true,toolName});
const create=(id:string,name:string,path:string,capability:string,properties:Record<string,unknown>,required:string[]=[],customerSafe=false,toolName?:string):ConnectorActionTemplate=>({id,name,description:`Create ${name.toLowerCase()} in the connected service.`,capability,method:"POST",pathTemplate:path,requestSchema:{type:"object",properties,required},requireConfirmation:true,customerSafe,toolName});

export const CONNECTORS: ConnectorDefinition[] = [
  {id:"woocommerce",name:"WooCommerce",category:"commerce",capabilities:["catalogue.read","orders.read","orders.write","checkout.create","inventory.read","analytics.read"],fields:[{key:"url",label:"Store URL",required:true,type:"url"},{key:"consumer_key",label:"Consumer key",required:true,secret:true},{key:"consumer_secret",label:"Consumer secret",required:true,secret:true},{key:"webhook_secret",label:"Webhook secret",secret:true}],nativeActions:[
    {id:"woo_search_products",name:"Search products",description:"Search the live WooCommerce catalogue.",capability:"catalogue.read",toolName:"search_products",native:true},
    {id:"woo_get_product",name:"Get product details",description:"Read live product details from WooCommerce.",capability:"catalogue.read",toolName:"get_product",native:true},
    {id:"woo_recommend_products",name:"Recommend products",description:"Recommend products from the live catalogue.",capability:"catalogue.read",toolName:"recommend_products",native:true},
    {id:"woo_track_order",name:"Track order",description:"Look up an order after customer ownership verification.",capability:"orders.read",toolName:"track_order",native:true},
    {id:"woo_create_checkout",name:"Create checkout",description:"Create a checkout for products selected in the conversation.",capability:"checkout.create",toolName:"create_checkout",native:true},
    {id:"woo_cancel_order",name:"Cancel order",description:"Cancel an eligible order. Sensitive action permissions and confirmation apply.",capability:"orders.write",toolName:"cancel_order",native:true},
    {id:"woo_modify_order",name:"Modify order",description:"Modify an eligible order. Sensitive action permissions and confirmation apply.",capability:"orders.write",toolName:"modify_order",native:true},
    {id:"woo_refund_order",name:"Refund order",description:"Refund an eligible order. Sensitive action permissions and confirmation apply.",capability:"orders.write",toolName:"refund_order",native:true},
    {id:"woo_inventory",name:"Inventory",description:"Read live stock levels for authorised internal assistants.",capability:"inventory.read",toolName:"inventory",native:true},
    {id:"woo_analytics",name:"Sales analytics",description:"Read sales and catalogue analytics for authorised internal assistants.",capability:"analytics.read",toolName:"analytics",native:true}
  ]},
  {id:"shopify",name:"Shopify",category:"commerce",capabilities:["catalogue.read","orders.read","inventory.read","checkout.create (with Storefront token)"],fields:[{key:"store_domain",label:"Store domain",required:true,placeholder:"your-store.myshopify.com"},{key:"access_token",label:"Admin GraphQL API access token",required:true,secret:true},{key:"api_version",label:"Admin API version",placeholder:"2026-07"},{key:"storefront_access_token",label:"Storefront API token (optional, enables checkout)",secret:true},{key:"storefront_api_version",label:"Storefront API version",placeholder:"2026-07"}],nativeActions:[
    {id:"shopify_search_products",name:"Search products",description:"Search the live Shopify catalogue.",capability:"catalogue.read",toolName:"search_products",native:true},
    {id:"shopify_get_product",name:"Get product details",description:"Read live product details from Shopify.",capability:"catalogue.read",toolName:"get_product",native:true},
    {id:"shopify_recommend_products",name:"Recommend products",description:"Recommend products from the live Shopify catalogue.",capability:"catalogue.read",toolName:"recommend_products",native:true},
    {id:"shopify_track_order",name:"Track order",description:"Look up an order after customer ownership verification.",capability:"orders.read",toolName:"track_order",native:true},
    {id:"shopify_create_checkout",name:"Create checkout",description:"Create checkout when a Storefront token is configured.",capability:"checkout.create",toolName:"create_checkout",native:true},
    {id:"shopify_inventory",name:"Inventory",description:"Read live Shopify stock levels for authorised internal assistants.",capability:"inventory.read",toolName:"inventory",native:true}
  ]},
  {id:"stripe",name:"Stripe",category:"payments",capabilities:["payments.read","payments.write"],fields:[{key:"secret_key",label:"Restricted/secret key",required:true,secret:true}],actionTemplates:[readList("Stripe customers","/v1/customers?limit=20","payments.read","list_customers"),readList("Stripe payment intents","/v1/payment_intents?limit=20","payments.read","list_payments")]},
  {id:"hubspot",name:"HubSpot",category:"crm",capabilities:["crm.read","crm.write","support.read","support.write"],fields:[{key:"access_token",label:"Private app / OAuth access token",required:true,secret:true},{key:"refresh_token",label:"OAuth refresh token",secret:true},{key:"client_id",label:"OAuth client ID"},{key:"client_secret",label:"OAuth client secret",secret:true}],actionTemplates:[readList("HubSpot contacts","/crm/v3/objects/contacts?limit=20","crm.read","list_contacts"),create("hubspot_create_contact","Create HubSpot contact","/crm/v3/objects/contacts","crm.write",{properties:{type:"object",description:"Contact properties such as email, firstname, lastname and phone"}},["properties"],true,"create_contact")]},
  {id:"salesforce",name:"Salesforce",category:"crm",capabilities:["crm.read","crm.write","support.read","support.write"],docsUrl:"https://developer.salesforce.com/docs/platform/api-rest/overview",fields:[{key:"instance_url",label:"Salesforce instance URL",required:true,type:"url",placeholder:"https://your-domain.my.salesforce.com"},{key:"access_token",label:"OAuth access token",required:true,secret:true},{key:"refresh_token",label:"OAuth refresh token",secret:true},{key:"client_id",label:"External client app ID"},{key:"client_secret",label:"External client app secret",secret:true},{key:"login_url",label:"OAuth login URL",type:"url",placeholder:"https://login.salesforce.com"}],actionTemplates:[readList("Salesforce limits","/limits","crm.read"),{id:"salesforce_query",name:"Run Salesforce query",description:"Run an administrator-approved SOQL query. Keep queries narrowly scoped and never request fields not needed for the customer request.",capability:"crm.read",method:"GET",pathTemplate:"/query",requestSchema:{type:"object",properties:{q:{type:"string"}},required:["q"]},requireConfirmation:false},create("salesforce_create_lead","Create Salesforce lead","/sobjects/Lead","crm.write",{FirstName:{type:"string"},LastName:{type:"string"},Company:{type:"string"},Email:{type:"string"},Phone:{type:"string"}},["LastName","Company"],true,"create_lead")]},
  {id:"intercom",name:"Intercom",category:"support",capabilities:["crm.read","crm.write","support.read","support.write"],docsUrl:"https://developers.intercom.com/docs/references/rest-api/api.intercom.io",fields:[{key:"access_token",label:"OAuth access token",required:true,secret:true},{key:"api_version",label:"Intercom API version",placeholder:"2.16"}],actionTemplates:[readList("Intercom contacts","/contacts?per_page=20","crm.read"),readList("Intercom conversations","/conversations?per_page=20","support.read"),create("intercom_create_contact","Create Intercom contact","/contacts","crm.write",{email:{type:"string"},name:{type:"string"},phone:{type:"string"}},["email"],true,"create_contact")]},
  {id:"freshdesk",name:"Freshdesk",category:"support",capabilities:["support.read","support.write","crm.read"],docsUrl:"https://developers.freshdesk.com/api/",fields:[{key:"base_url",label:"Freshdesk URL",required:true,type:"url",placeholder:"https://company.freshdesk.com"},{key:"api_key",label:"API key",required:true,secret:true}],actionTemplates:[readList("Freshdesk tickets","/tickets","support.read"),create("freshdesk_create_ticket","Create Freshdesk ticket","/tickets","support.write",{email:{type:"string"},subject:{type:"string"},description:{type:"string"},priority:{type:"integer",enum:[1,2,3,4]},status:{type:"integer",enum:[2,3,4,5]}},["email","subject","description","priority","status"],true,"create_support_ticket")]},
  {id:"helpscout",name:"Help Scout",category:"support",capabilities:["support.read","support.write","crm.read"],docsUrl:"https://developer.helpscout.com/mailbox-api/",fields:[{key:"access_token",label:"OAuth access token",required:true,secret:true},{key:"refresh_token",label:"OAuth refresh token",secret:true},{key:"app_id",label:"OAuth application ID"},{key:"app_secret",label:"OAuth application secret",secret:true}],actionTemplates:[readList("Help Scout conversations","/conversations","support.read"),readList("Help Scout customers","/customers","crm.read")]},
  {id:"gorgias",name:"Gorgias",category:"support",capabilities:["support.read","support.write","crm.read","crm.write"],docsUrl:"https://developers.gorgias.com/reference/introduction",fields:[{key:"base_url",label:"Gorgias account URL",required:true,type:"url",placeholder:"https://your-domain.gorgias.com"},{key:"username",label:"API username / email"},{key:"api_key",label:"Private app API key",secret:true},{key:"access_token",label:"OAuth access token (public apps)",secret:true}],actionTemplates:[readList("Gorgias tickets","/tickets","support.read"),readList("Gorgias customers","/customers","crm.read")]},
  {id:"zoho_desk",name:"Zoho Desk",category:"support",capabilities:["support.read","support.write","crm.read","crm.write"],docsUrl:"https://desk.zoho.com/DeskAPIDocument",fields:[{key:"base_url",label:"Zoho Desk API host",required:true,type:"url",placeholder:"https://desk.zoho.com"},{key:"org_id",label:"Organization ID",required:true},{key:"access_token",label:"OAuth access token",required:true,secret:true},{key:"refresh_token",label:"OAuth refresh token",secret:true},{key:"client_id",label:"OAuth client ID"},{key:"client_secret",label:"OAuth client secret",secret:true},{key:"accounts_url",label:"Zoho Accounts host",type:"url",placeholder:"https://accounts.zoho.com"}],actionTemplates:[readList("Zoho Desk tickets","/tickets","support.read"),readList("Zoho Desk contacts","/contacts","crm.read")]},
  {id:"zendesk",name:"Zendesk",category:"support",capabilities:["support.read","support.write","knowledge.read"],sourceKinds:["zendesk"],fields:[{key:"base_url",label:"Zendesk URL",required:true,type:"url",placeholder:"https://company.zendesk.com"},{key:"email",label:"Agent email"},{key:"token",label:"API token",secret:true},{key:"access_token",label:"OAuth access token",secret:true}],actionTemplates:[readList("Zendesk tickets","/api/v2/tickets","support.read","list_support_tickets")]},
  {id:"slack",name:"Slack",category:"messaging",capabilities:["messaging.send"],fields:[{key:"bot_token",label:"Bot token",required:true,secret:true},{key:"refresh_token",label:"OAuth refresh token",secret:true},{key:"client_id",label:"OAuth client ID"},{key:"client_secret",label:"OAuth client secret",secret:true}],actionTemplates:[{id:"slack_list_channels",name:"List Slack channels",description:"List channels available to the connected workspace.",capability:"messaging.read",method:"GET",pathTemplate:"/api/conversations.list?limit=100",requestSchema:{type:"object",properties:{}},requireConfirmation:false,customerSafe:true,toolName:"list_message_channels"},create("slack_send_message","Send Slack message","/api/chat.postMessage","messaging.send",{channel:{type:"string"},text:{type:"string"}},["channel","text"],false,"send_internal_message")]},
  {id:"whatsapp",name:"WhatsApp Cloud API",category:"messaging",capabilities:["messaging.send"],fields:[{key:"access_token",label:"Access token",required:true,secret:true},{key:"phone_number_id",label:"Phone number ID",required:true},{key:"graph_version",label:"Graph API version",placeholder:"v24.0"}],actionTemplates:[create("whatsapp_send_message","Send WhatsApp message","/{phone_number_id}/messages","messaging.send",{messaging_product:{type:"string",enum:["whatsapp"]},to:{type:"string"},type:{type:"string"},text:{type:"object"}},["messaging_product","to","type","text"],false,"send_whatsapp_message")]},
  {id:"messenger",name:"Facebook Messenger",category:"messaging",capabilities:["messaging.read","messaging.send"],docsUrl:"https://developers.facebook.com/docs/messenger-platform/",fields:[{key:"page_id",label:"Facebook Page ID",required:true},{key:"page_access_token",label:"Page access token",required:true,secret:true},{key:"graph_version",label:"Graph API version",placeholder:"v24.0"}],actionTemplates:[create("messenger_send","Send Messenger message","/{page_id}/messages","messaging.send",{recipient:{type:"object"},message:{type:"object"},messaging_type:{type:"string"}},["recipient","message"])]},
  {id:"instagram",name:"Instagram Messaging",category:"messaging",capabilities:["messaging.read","messaging.send"],docsUrl:"https://developers.facebook.com/docs/instagram-platform/",fields:[{key:"instagram_account_id",label:"Instagram professional account ID",required:true},{key:"access_token",label:"Access token",required:true,secret:true},{key:"graph_version",label:"Graph API version",placeholder:"v24.0"}],actionTemplates:[create("instagram_send","Send Instagram message","/{instagram_account_id}/messages","messaging.send",{recipient:{type:"object"},message:{type:"object"}},["recipient","message"])]},
  {id:"twilio",name:"Twilio",category:"messaging",capabilities:["messaging.read","messaging.send"],docsUrl:"https://www.twilio.com/docs/messaging/api",fields:[{key:"account_sid",label:"Account SID",required:true},{key:"auth_token",label:"Auth token",required:true,secret:true},{key:"messaging_service_sid",label:"Messaging Service SID"},{key:"from_number",label:"From number",placeholder:"+441234567890"}],actionTemplates:[create("twilio_send_sms","Send SMS","/Messages.json","messaging.send",{To:{type:"string"},Body:{type:"string"},From:{type:"string"},MessagingServiceSid:{type:"string"}},["To","Body"])]},
  {id:"calendly",name:"Calendly",category:"scheduling",capabilities:["calendar.read","calendar.write"],docsUrl:"https://developer.calendly.com/",fields:[{key:"access_token",label:"Personal/OAuth access token",required:true,secret:true},{key:"refresh_token",label:"OAuth refresh token",secret:true},{key:"client_id",label:"OAuth client ID"},{key:"client_secret",label:"OAuth client secret",secret:true}],actionTemplates:[
    {id:"calendly_list_event_types",name:"List Calendly event types",description:"List the connected Calendly user's active meeting types and scheduling links. Use this when a customer asks what meetings they can book.",capability:"calendar.read",method:"GET",pathTemplate:"/event_types",requestSchema:{type:"object",properties:{}},responseMapping:{path:"collection"},requireConfirmation:false,customerSafe:true,toolName:"list_appointment_types"},
    {id:"calendly_available_times",name:"Check Calendly availability",description:"Find live available appointment times for a selected Calendly event type. start_time and end_time must be future ISO-8601 UTC timestamps and the range must not exceed 31 days.",capability:"calendar.read",method:"GET",pathTemplate:"/event_type_available_times",requestSchema:{type:"object",properties:{event_type:{type:"string",description:"Calendly event type URI"},start_time:{type:"string",description:"Future ISO-8601 UTC start"},end_time:{type:"string",description:"Future ISO-8601 UTC end, within 31 days"}},required:["event_type","start_time","end_time"]},responseMapping:{path:"collection"},requireConfirmation:false,customerSafe:true,toolName:"check_appointment_availability"},
    {id:"calendly_book_invitee",name:"Book Calendly appointment",description:"Book the customer's explicitly selected available Calendly time. Only use after the customer has chosen the time and supplied the invitee details. This action requires explicit confirmation before booking.",capability:"calendar.write",method:"POST",pathTemplate:"/invitees",requestSchema:{type:"object",properties:{event_type:{type:"string"},start_time:{type:"string"},invitee:{type:"object"},location:{type:"object"},questions_and_answers:{type:"array"},event_guests:{type:"array"}},required:["event_type","start_time","invitee"]},responseMapping:{path:"resource",fields:["uri","event","name","email","status","timezone","cancel_url","reschedule_url"]},requireConfirmation:true,customerSafe:true,toolName:"book_appointment"}
  ]},
  {id:"notion",name:"Notion",category:"knowledge",capabilities:["knowledge.read"],sourceKinds:["notion"],fields:[{key:"token",label:"Internal/OAuth access token",required:true,secret:true},{key:"refresh_token",label:"OAuth refresh token",secret:true}],actionTemplates:[{id:"notion_search",name:"Search Notion",description:"Search the connected Notion workspace for pages and databases.",capability:"knowledge.read",method:"POST",pathTemplate:"/v1/search",requestSchema:{type:"object",properties:{query:{type:"string"},page_size:{type:"integer"}}},requireConfirmation:false,customerSafe:true,toolName:"search_connected_knowledge"}]},
  {id:"google_drive",name:"Google Drive",category:"knowledge",capabilities:["knowledge.read"],sourceKinds:["google_drive"],fields:[{key:"access_token",label:"OAuth access token",secret:true},{key:"refresh_token",label:"OAuth refresh token",secret:true},{key:"client_id",label:"OAuth client ID"},{key:"client_secret",label:"OAuth client secret",secret:true}],actionTemplates:[{id:"drive_list_files",name:"List Google Drive files",description:"List files from the connected Google Drive.",capability:"knowledge.read",method:"GET",pathTemplate:"/drive/v3/files",requestSchema:{type:"object",properties:{q:{type:"string"},pageSize:{type:"integer"},fields:{type:"string"}}},requireConfirmation:false,customerSafe:true,toolName:"list_connected_files"}]},
  {id:"dropbox",name:"Dropbox",category:"knowledge",capabilities:["knowledge.read"],sourceKinds:["dropbox"],fields:[{key:"access_token",label:"Access token",required:true,secret:true},{key:"refresh_token",label:"Refresh token",secret:true},{key:"app_key",label:"App key"},{key:"app_secret",label:"App secret",secret:true}],actionTemplates:[{id:"dropbox_list_folder",name:"List Dropbox folder",description:"List files and folders in the connected Dropbox path.",capability:"knowledge.read",method:"POST",pathTemplate:"/2/files/list_folder",requestSchema:{type:"object",properties:{path:{type:"string"},recursive:{type:"boolean"},limit:{type:"integer"}},required:["path"]},requireConfirmation:false,customerSafe:true,toolName:"list_connected_files"}]},
  {id:"wordpress",name:"WordPress",category:"cms",capabilities:["knowledge.read","cms.read","cms.write"],docsUrl:"https://developer.wordpress.org/rest-api/",fields:[{key:"url",label:"WordPress site URL",required:true,type:"url"},{key:"username",label:"WordPress username",required:true},{key:"app_password",label:"Application password",required:true,secret:true}],actionTemplates:[readList("WordPress posts","/posts?per_page=20","cms.read"),readList("WordPress pages","/pages?per_page=20","cms.read"),create("wordpress_create_post","Create WordPress post","/posts","cms.write",{title:{type:"string"},content:{type:"string"},status:{type:"string",enum:["draft","publish","pending","private"]}},["title","content"])]},
  {id:"supabase",name:"Supabase",category:"database",capabilities:["business_data.read","catalogue.read","orders.read"],fields:[{key:"url",label:"Project URL",required:true,type:"url"},{key:"anon_key",label:"Anon key",required:true,secret:true},{key:"capability_config",label:"Capability mapping JSON",type:"textarea"},{key:"query_policy",label:"Business-data policy JSON",type:"textarea"}],nativeActions:[
    {id:"supabase_search_products",name:"Search products",description:"Search the connected Supabase catalogue. ZoChat discovers product, variant, price, stock and option fields from the exposed schema; an explicit mapping can override discovery.",capability:"catalogue.read",toolName:"search_products",native:true},
    {id:"supabase_get_product",name:"Get product details",description:"Read product details from the configured Supabase catalogue.",capability:"catalogue.read",toolName:"get_product",native:true},
    {id:"supabase_track_order",name:"Track order",description:"Read order status when an orders mapping is configured.",capability:"orders.read",toolName:"track_order",native:true},
    {id:"supabase_search_business_data",name:"Search business data",description:"Read only the logical business resources allowed by the configured Supabase query policy.",capability:"business_data.read",toolName:"search_business_data",native:true}
  ]},
  {id:"resend",name:"Resend",category:"email",capabilities:["email.send"],fields:[{key:"api_key",label:"API key",required:true,secret:true},{key:"from_email",label:"From email",required:true},{key:"from_name",label:"From name"}],actionTemplates:[{id:"resend_send_email",name:"Send email",description:"Send an email using the workspace-configured sender. The assistant must provide the recipient, subject and complete message body itself; never ask the customer for technical email fields.",capability:"email.send",method:"POST",pathTemplate:"/emails",requestSchema:{type:"object",properties:{to:{type:"array",items:{type:"string",format:"email"},title:"Recipient email"},subject:{type:"string",title:"Subject"},text:{type:"string",title:"Message"},html:{type:"string",title:"HTML message"}},required:["to","subject","text"]},requireConfirmation:true,customerSafe:false,toolName:"send_email"}]},
  {id:"zapier",name:"Zapier",category:"automation",capabilities:["automation.trigger"],fields:[{key:"webhook_url",label:"Catch Hook URL",required:true,type:"url",secret:true},{key:"signing_secret",label:"Signing secret",secret:true}],actionTemplates:[create("zapier_trigger","Trigger Zapier automation","/","automation.trigger",{payload:{type:"object"}},[],false,"trigger_automation")]},
  {id:"make",name:"Make",category:"automation",capabilities:["automation.trigger"],fields:[{key:"webhook_url",label:"Webhook URL",required:true,type:"url",secret:true},{key:"signing_secret",label:"Signing secret",secret:true}],actionTemplates:[create("make_trigger","Trigger Make automation","/","automation.trigger",{payload:{type:"object"}},[],false,"trigger_automation")]},
  {id:"n8n",name:"n8n",category:"automation",capabilities:["automation.trigger"],fields:[{key:"webhook_url",label:"Webhook URL",required:true,type:"url",secret:true},{key:"api_key",label:"API key",secret:true}],actionTemplates:[create("n8n_trigger","Trigger n8n automation","/","automation.trigger",{payload:{type:"object"}},[],false,"trigger_automation")]},
  {id:"webhook",name:"Generic Webhook",category:"developer",capabilities:["automation.trigger"],fields:[{key:"url",label:"Webhook URL",required:true,type:"url",secret:true},{key:"authorization",label:"Authorization header",secret:true}],actionTemplates:[create("webhook_trigger","Trigger webhook","/","automation.trigger",{payload:{type:"object"}},[],false,"trigger_automation")]},
  {id:"custom_api",name:"Custom REST API",category:"developer",capabilities:["custom.read","custom.write"],fields:[{key:"base_url",label:"Base URL",required:true,type:"url"},{key:"auth_type",label:"Auth type",placeholder:"bearer | api_key | basic | none"},{key:"api_key",label:"API key / bearer token",secret:true},{key:"header_name",label:"API key header",placeholder:"X-API-Key"},{key:"username",label:"Basic auth username"},{key:"password",label:"Basic auth password",secret:true}]},
];

const SECRET_FIELDS = new Set(CONNECTORS.flatMap(c=>c.fields.filter(f=>f.secret).map(f=>`${c.id}:${f.key}`)));
export function definition(provider:string):ConnectorDefinition|undefined{return CONNECTORS.find(c=>c.id===provider)}
export function actionTemplateFor(provider:string,name:string){return definition(provider)?.actionTemplates?.find(t=>t.name===name)}
export function isBuiltInAction(provider:string,name:string,method?:string,pathTemplate?:string):boolean{
  const t=actionTemplateFor(provider,name);
  return Boolean(t&&(!method||t.method===method)&&(!pathTemplate||t.pathTemplate===pathTemplate));
}

export function isSecretField(provider:string,key:string):boolean{return SECRET_FIELDS.has(`${provider}:${key}`)}

export async function encryptCredentials(provider:string,input:Record<string,unknown>,existing:Record<string,unknown>={}):Promise<Record<string,unknown>>{
  const def=definition(provider); if(!def)throw new Error("Unsupported connector"); const out:Record<string,unknown>={...existing};
  for(const field of def.fields){if(!(field.key in input))continue;let value=input[field.key];if(typeof value==="string")value=value.trim();if(value===""||value==null){continue}out[field.key]=field.secret?await encryptSecret(String(value)):value}
  return out;
}
export async function decryptedCredentials(provider:string,input:Record<string,unknown>):Promise<Record<string,unknown>>{
  const out:Record<string,unknown>={...input};const def=definition(provider);if(!def)return out;for(const f of def.fields){if(f.secret&&out[f.key])out[f.key]=await decryptSecret(out[f.key])}return out;
}
export function publicCredentialSummary(provider:string,credentials:Record<string,unknown>):Record<string,unknown>{
  const def=definition(provider);const out:Record<string,unknown>={};if(!def)return out;for(const f of def.fields){const v=credentials[f.key];if(f.secret){out[`has_${f.key}`]=Boolean(v)}else if(v!=null)out[f.key]=v}return out;
}

function isPrivateHost(h:string){h=h.toLowerCase().replace(/^\[|\]$/g,"");return h==="localhost"||h.endsWith(".localhost")||h==="::1"||/^127\./.test(h)||/^10\./.test(h)||/^192\.168\./.test(h)||/^169\.254\./.test(h)||(/^172\.(\d+)\./.test(h)&&(()=>{const n=Number(h.split(".")[1]);return n>=16&&n<=31})())||h.startsWith("fc")||h.startsWith("fd")||h.startsWith("fe80:")}
async function externalHttps(raw:string,label="URL"):Promise<URL>{
  let u:URL;try{u=new URL(raw)}catch{throw new Error(`${label} is invalid`)}
  if(u.protocol!=="https:")throw new Error(`${label} must use HTTPS`);if(u.username||u.password||isPrivateHost(u.hostname))throw new Error(`${label} cannot target a private/internal network`);
  try{const ips=await Deno.resolveDns(u.hostname,"A");if(ips.some(isPrivateHost))throw new Error(`${label} resolves to a private/internal network`)}catch(e){if(e instanceof Error&&e.message.includes("private/internal"))throw e}return u;
}
async function timedFetch(input:string|URL,init:RequestInit={}):Promise<Response>{const ctrl=new AbortController();const t=setTimeout(()=>ctrl.abort(),10000);try{return await fetch(input,{...init,signal:ctrl.signal,redirect:init.redirect??"manual"})}finally{clearTimeout(t)}}
function normDomain(v:string){return v.trim().replace(/^https?:\/\//i,"").replace(/\/$/,"")}
function basic(v:string){return `Basic ${btoa(v)}`}
function normalizedBase(raw:unknown,label:string){return externalHttps(String(raw??""),label)}

export async function testConnector(provider:string,creds:Record<string,unknown>):Promise<{ok:boolean;message:string}>{
  const c=await decryptedCredentials(provider,creds);let r:Response;
  switch(provider){
    case"woocommerce":{const base=(await normalizedBase(c.url,"WooCommerce URL")).toString().replace(/\/$/,"");const u=new URL(`${base}/wp-json/wc/v3/system_status`);u.searchParams.set("consumer_key",String(c.consumer_key??""));u.searchParams.set("consumer_secret",String(c.consumer_secret??""));r=await timedFetch(u,{headers:{Accept:"application/json"}});break}
    case"shopify":{const d=normDomain(String(c.store_domain??""));if(!/^[a-z0-9][a-z0-9-]*\.myshopify\.com$/i.test(d))throw new Error("Shopify store domain must be a *.myshopify.com domain");const version=String(c.api_version??"2026-07");r=await timedFetch(`https://${d}/admin/api/${version}/graphql.json`,{method:"POST",headers:{"X-Shopify-Access-Token":String(c.access_token??""),"Content-Type":"application/json",Accept:"application/json"},body:JSON.stringify({query:"query ZoChatConnectionTest { shop { name } }"})});break}
    case"stripe":r=await timedFetch("https://api.stripe.com/v1/account",{headers:{Authorization:`Bearer ${String(c.secret_key??"")}`}});break;
    case"hubspot":r=await timedFetch("https://api.hubapi.com/crm/v3/objects/contacts?limit=1",{headers:{Authorization:`Bearer ${String(c.access_token??"")}`}});break;
    case"salesforce":{const base=(await normalizedBase(c.instance_url,"Salesforce instance URL")).toString().replace(/\/$/,"");r=await timedFetch(`${base}/services/data/latest/limits`,{headers:{Authorization:`Bearer ${String(c.access_token??"")}`,Accept:"application/json"}});break}
    case"intercom":r=await timedFetch("https://api.intercom.io/contacts?per_page=1",{headers:{Authorization:`Bearer ${String(c.access_token??"")}`,"Intercom-Version":String(c.api_version??"2.16"),Accept:"application/json"}});break;
    case"freshdesk":{const base=(await normalizedBase(c.base_url,"Freshdesk URL")).toString().replace(/\/$/,"");r=await timedFetch(`${base}/api/v2/tickets?per_page=1`,{headers:{Authorization:basic(`${String(c.api_key??"")}:X`),Accept:"application/json"}});break}
    case"helpscout":r=await timedFetch("https://api.helpscout.net/v2/users/me",{headers:{Authorization:`Bearer ${String(c.access_token??"")}`,Accept:"application/json"}});break;
    case"gorgias":{const base=(await normalizedBase(c.base_url,"Gorgias URL")).toString().replace(/\/$/,"");const auth=c.access_token?`Bearer ${String(c.access_token)}`:basic(`${String(c.username??"")}:${String(c.api_key??"")}`);r=await timedFetch(`${base}/api/account`,{headers:{Authorization:auth,Accept:"application/json"}});break}
    case"zoho_desk":{const base=(await normalizedBase(c.base_url,"Zoho Desk URL")).toString().replace(/\/$/,"");r=await timedFetch(`${base}/api/v1/tickets?limit=1`,{headers:{Authorization:`Zoho-oauthtoken ${String(c.access_token??"")}`,orgId:String(c.org_id??""),Accept:"application/json"}});break}
    case"zendesk":{const base=(await normalizedBase(c.base_url,"Zendesk URL")).toString().replace(/\/$/,"");const auth=c.access_token?`Bearer ${c.access_token}`:basic(`${c.email}/token:${c.token}`);r=await timedFetch(`${base}/api/v2/account/settings.json`,{headers:{Authorization:String(auth),Accept:"application/json"}});break}
    case"slack":r=await timedFetch("https://slack.com/api/auth.test",{method:"POST",headers:{Authorization:`Bearer ${String(c.bot_token??"")}`,"Content-Type":"application/x-www-form-urlencoded"},body:""});break;
    case"whatsapp":{const version=String(c.graph_version??"v24.0");const id=encodeURIComponent(String(c.phone_number_id??""));r=await timedFetch(`https://graph.facebook.com/${version}/${id}?fields=display_phone_number,verified_name`,{headers:{Authorization:`Bearer ${String(c.access_token??"")}`}});break}
    case"messenger":{const version=String(c.graph_version??"v24.0");const id=encodeURIComponent(String(c.page_id??""));r=await timedFetch(`https://graph.facebook.com/${version}/${id}?fields=id,name`,{headers:{Authorization:`Bearer ${String(c.page_access_token??"")}`}});break}
    case"instagram":{const version=String(c.graph_version??"v24.0");const id=encodeURIComponent(String(c.instagram_account_id??""));r=await timedFetch(`https://graph.facebook.com/${version}/${id}?fields=id,username`,{headers:{Authorization:`Bearer ${String(c.access_token??"")}`}});break}
    case"twilio":{const sid=encodeURIComponent(String(c.account_sid??""));r=await timedFetch(`https://api.twilio.com/2010-04-01/Accounts/${sid}.json`,{headers:{Authorization:basic(`${String(c.account_sid??"")}:${String(c.auth_token??"")}`),Accept:"application/json"}});break}
    case"calendly":r=await timedFetch("https://api.calendly.com/users/me",{headers:{Authorization:`Bearer ${String(c.access_token??"")}`}});break;
    case"notion":r=await timedFetch("https://api.notion.com/v1/users/me",{headers:{Authorization:`Bearer ${String(c.token??"")}`,"Notion-Version":"2026-03-11"}});break;
    case"google_drive":r=await timedFetch("https://www.googleapis.com/drive/v3/about?fields=user",{headers:{Authorization:`Bearer ${String(c.access_token??"")}`}});break;
    case"dropbox":r=await timedFetch("https://api.dropboxapi.com/2/users/get_current_account",{method:"POST",headers:{Authorization:`Bearer ${String(c.access_token??"")}`,"Content-Type":"application/json"},body:"null"});break;
    case"wordpress":{const base=(await normalizedBase(c.url,"WordPress URL")).toString().replace(/\/$/,"");r=await timedFetch(`${base}/wp-json/wp/v2/users/me?context=edit`,{headers:{Authorization:basic(`${String(c.username??"")}:${String(c.app_password??"")}`),Accept:"application/json"}});break}
    case"supabase":{const base=(await normalizedBase(c.url,"Supabase URL")).toString().replace(/\/$/,"");r=await timedFetch(`${base}/rest/v1/`,{headers:{apikey:String(c.anon_key??""),Authorization:`Bearer ${String(c.anon_key??"")}`}});break}
    case"resend":r=await timedFetch("https://api.resend.com/domains",{headers:{Authorization:`Bearer ${String(c.api_key??"")}`}});break;
    case"zapier":case"make":case"n8n":case"webhook":{const raw=String(c.webhook_url??c.url??"");const u=await externalHttps(raw,"Webhook URL");r=await timedFetch(u,{method:"HEAD",redirect:"manual"});if(r.status===405||r.status===404)return{ok:true,message:"Webhook URL is configured (endpoint does not support HEAD testing)"};break}
    case"custom_api":{const base=(await normalizedBase(c.base_url,"Custom API base URL")).toString().replace(/\/$/,"");const headers:Record<string,string>={Accept:"application/json"};const auth=String(c.auth_type??"none");if(auth==="bearer")headers.Authorization=`Bearer ${String(c.api_key??"")}`;if(auth==="api_key")headers[String(c.header_name??"X-API-Key")]=String(c.api_key??"");if(auth==="basic")headers.Authorization=basic(`${c.username??""}:${c.password??""}`);r=await timedFetch(base,{method:"GET",headers,redirect:"manual"});break}
    default:throw new Error("Unsupported connector");
  }
  if(provider==="slack"&&r.ok){const d=await r.clone().json().catch(()=>({})) as any;if(d.ok===false)return{ok:false,message:String(d.error??"Slack rejected credentials")}}
  if(!r.ok){const text=(await r.text().catch(()=>"")).slice(0,300);return{ok:false,message:`Connection failed (${r.status})${text?`: ${text.replace(/\s+/g," ")}`:""}`};}
  return{ok:true,message:"Connection verified"};
}
