import { DashboardError, resolveDashboardContext, requireDashboardRole } from "../_shared/dashboard.ts";
import { handleOptions, json } from "../_shared/cors.ts";
import { supabaseConfig } from "../_shared/env.ts";
import { audit } from "../_shared/audit.ts";
import { enqueueJob } from "../_shared/jobs.ts";
import { CONNECTORS, definition, encryptCredentials, publicCredentialSummary, testConnector } from "../_shared/connectors/registry.ts";
import { requirePlanFeature } from "../_shared/entitlements.ts";
import { oauthAvailable } from "../_shared/connectors/oauth.ts";
import { ensureDefaultConnectorActions } from "../_shared/connectors/default-actions.ts";

const SOURCE_KINDS = new Set(["file","website","sitemap","url","text","qa","notion","google_drive","dropbox","zendesk","wordpress"]);
const REMOTE_CONNECTION: Record<string,string|undefined> = { notion:"notion",google_drive:"google_drive",dropbox:"dropbox",zendesk:"zendesk",wordpress:"wordpress" };

function c(){const {url,serviceRoleKey}=supabaseConfig();return{base:`${url.replace(/\/+$/g,"")}/rest/v1`,storage:`${url.replace(/\/+$/g,"")}/storage/v1`,h:{apikey:serviceRoleKey,Authorization:`Bearer ${serviceRoleKey}`,"Content-Type":"application/json"}}}
async function rows(path:string,qs:Record<string,string>){const x=c();const r=await fetch(`${x.base}/${path}?${new URLSearchParams(qs)}`,{headers:x.h});if(!r.ok)throw new DashboardError("Database operation failed",502);return r.json() as Promise<Record<string,unknown>[]>}
async function write(method:string,path:string,body:Record<string,unknown>,prefer="return=minimal"){const x=c();const r=await fetch(`${x.base}/${path}`,{method,headers:{...x.h,Prefer:prefer},body:JSON.stringify(body)});if(!r.ok){console.error("data-sources db write",r.status,(await r.text()).slice(0,400));throw new DashboardError("Database operation failed",502)}return r}
function cleanName(v:unknown,max=160){return String(v??"").trim().replace(/[\u0000-\u001f]/g," ").slice(0,max)}
function safeFileName(v:string){return v.replace(/[^A-Za-z0-9._ -]/g,"_").replace(/\s+/g,"-").slice(0,180)||"source"}
async function assertBot(tenantId:string,chatbotId:string){const r=await rows("chatbots",{id:`eq.${chatbotId}`,tenant_id:`eq.${tenantId}`,select:"id",limit:"1"});if(!r[0])throw new DashboardError("Assistant not found",404)}
async function assertSource(tenantId:string,id:string){const r=await rows("data_sources",{id:`eq.${id}`,tenant_id:`eq.${tenantId}`,select:"*",limit:"1"});if(!r[0])throw new DashboardError("Source not found",404);return r[0]}
function validateUrl(raw:unknown,label="URL"){let u:URL;try{u=new URL(String(raw??""))}catch{throw new DashboardError(`${label} is invalid`,400)}if(!["http:","https:"].includes(u.protocol))throw new DashboardError(`${label} must use HTTP or HTTPS`,400);if(u.username||u.password)throw new DashboardError(`${label} cannot contain credentials`,400);return u.toString()}
function validateSourceConfig(kind:string,raw:unknown):Record<string,unknown>{
  const inCfg=(raw&&typeof raw==="object"&&!Array.isArray(raw)?raw:{}) as Record<string,unknown>;const out:Record<string,unknown>={};
  if(kind==="website"){out.url=validateUrl(inCfg.url,"Website URL");out.maxPages=Math.min(500,Math.max(1,Number(inCfg.maxPages??100)));out.maxDepth=Math.min(5,Math.max(0,Number(inCfg.maxDepth??2)));out.includePaths=Array.isArray(inCfg.includePaths)?inCfg.includePaths.map(x=>String(x).slice(0,300)).slice(0,50):[];out.excludePaths=Array.isArray(inCfg.excludePaths)?inCfg.excludePaths.map(x=>String(x).slice(0,300)).slice(0,50):[]}
  else if(kind==="sitemap"||kind==="url"){out.url=validateUrl(inCfg.url,kind==="sitemap"?"Sitemap URL":"Page URL");if(kind==="sitemap")out.maxPages=Math.min(1000,Math.max(1,Number(inCfg.maxPages??250)))}
  else if(kind==="text"){const content=String(inCfg.content??"").trim();if(!content)throw new DashboardError("Text content is required");if(content.length>2_000_000)throw new DashboardError("Text source is too large");out.content=content}
  else if(kind==="qa"){const pairs=Array.isArray(inCfg.pairs)?inCfg.pairs:[];const clean=pairs.slice(0,1000).map((p:any)=>({question:String(p?.question??"").trim().slice(0,3000),answer:String(p?.answer??"").trim().slice(0,12000)})).filter((p:any)=>p.question&&p.answer);if(!clean.length)throw new DashboardError("At least one complete Q&A pair is required");out.pairs=clean}
  else if(kind==="file"){const fileName=cleanName(inCfg.fileName,180);if(!fileName)throw new DashboardError("File name is required");out.fileName=fileName;out.mimeType=cleanName(inCfg.mimeType,120);out.size=Number(inCfg.size??0)}
  else if(kind==="google_drive"){if(inCfg.folderId)out.folderId=cleanName(inCfg.folderId,300)}
  else if(kind==="dropbox"){out.path=String(inCfg.path??"").trim().slice(0,1000)}
  return out;
}

async function listSources(tenantId:string,url:URL){const chatbotId=url.searchParams.get("chatbotId")?.trim();const qs:Record<string,string>={tenant_id:`eq.${tenantId}`,select:"id,tenant_id,chatbot_id,kind,name,status,config,connection_provider,object_path,sync_interval_minutes,next_sync_at,last_sync_at,last_error,document_count,chunk_count,created_at,updated_at",order:"updated_at.desc",limit:"1000"};if(chatbotId)qs.chatbot_id=`eq.${chatbotId}`;const items=await rows("data_sources",qs);return json({items})}
async function createSource(ctx:Awaited<ReturnType<typeof resolveDashboardContext>>,req:Request){requireDashboardRole(ctx,"admin");const b=await req.json().catch(()=>({})) as Record<string,unknown>;const kind=String(b.kind??"");if(!SOURCE_KINDS.has(kind))throw new DashboardError("Unsupported source type");const chatbotId=String(b.chatbotId??"").trim();if(!chatbotId)throw new DashboardError("chatbotId is required");await assertBot(ctx.tenantId,chatbotId);const name=cleanName(b.name)||`${kind.replace(/_/g," ")} source`;const config=validateSourceConfig(kind,b.config);const syncRaw=b.syncIntervalMinutes;const sync=syncRaw==null||syncRaw===""?null:Math.min(10080,Math.max(15,Number(syncRaw)));const provider=REMOTE_CONNECTION[kind]??null;if(provider){requirePlanFeature(ctx.tenant,"liveIntegrations");const integ=await rows("integrations",{tenant_id:`eq.${ctx.tenantId}`,provider:`eq.${provider}`,active:"eq.true",select:"id",limit:"1"});if(!integ[0])throw new DashboardError(`Connect ${definition(provider)?.name??provider} before adding this source`,409)}const id=crypto.randomUUID();let objectPath:string|null=null;if(kind==="file")objectPath=`${ctx.tenantId}/${chatbotId}/${id}/${safeFileName(String(config.fileName))}`;const res=await write("POST","data_sources",{id,tenant_id:ctx.tenantId,chatbot_id:chatbotId,kind,name,status:"pending",config,connection_provider:provider,object_path:objectPath,sync_interval_minutes:sync,created_by:ctx.user.id},"return=representation");const created=(await res.json()) as Record<string,unknown>[];await audit(ctx,"data_source.created","data_source",id,{kind});if(kind!=="file")await enqueueJob(ctx.tenantId,"source_sync",{sourceId:id});return json({item:created[0],uploadPath:objectPath},201)}
async function updateSource(ctx:Awaited<ReturnType<typeof resolveDashboardContext>>,req:Request,url:URL){requireDashboardRole(ctx,"admin");const id=url.searchParams.get("id");if(!id)throw new DashboardError("id is required");const prior=await assertSource(ctx.tenantId,id);const b=await req.json().catch(()=>({})) as Record<string,unknown>;const patch:Record<string,unknown>={updated_at:new Date().toISOString()};if("name"in b)patch.name=cleanName(b.name)||prior.name;if("config"in b)patch.config=validateSourceConfig(String(prior.kind),b.config);if("syncIntervalMinutes"in b){patch.sync_interval_minutes=b.syncIntervalMinutes==null||b.syncIntervalMinutes===""?null:Math.min(10080,Math.max(15,Number(b.syncIntervalMinutes)));patch.next_sync_at=patch.sync_interval_minutes?new Date(Date.now()+Number(patch.sync_interval_minutes)*60000).toISOString():null}if("paused"in b)patch.status=b.paused?"paused":"ready";await write("PATCH",`data_sources?id=eq.${id}&tenant_id=eq.${ctx.tenantId}`,patch);await audit(ctx,"data_source.updated","data_source",id);return json({ok:true})}
async function deleteSource(ctx:Awaited<ReturnType<typeof resolveDashboardContext>>,url:URL){requireDashboardRole(ctx,"admin");const id=url.searchParams.get("id");if(!id)throw new DashboardError("id is required");const prior=await assertSource(ctx.tenantId,id);if(prior.object_path){const x=c();await fetch(`${x.storage}/object/knowledge-sources/${String(prior.object_path).split("/").map(encodeURIComponent).join("/")}`,{method:"DELETE",headers:{apikey:x.h.apikey,Authorization:x.h.Authorization}}).catch(()=>undefined)}await write("DELETE",`data_sources?id=eq.${id}&tenant_id=eq.${ctx.tenantId}`,{});await audit(ctx,"data_source.deleted","data_source",id,{kind:prior.kind});return json({ok:true})}
async function syncNow(ctx:Awaited<ReturnType<typeof resolveDashboardContext>>,url:URL){requireDashboardRole(ctx,"admin");const id=url.searchParams.get("id");if(!id)throw new DashboardError("id is required");const src=await assertSource(ctx.tenantId,id);if(src.kind==="file"&&!src.object_path)throw new DashboardError("File has not been uploaded");await write("PATCH",`data_sources?id=eq.${id}`,{status:"pending",last_error:null,updated_at:new Date().toISOString()});const jobId=await enqueueJob(ctx.tenantId,"source_sync",{sourceId:id});await audit(ctx,"data_source.sync_requested","data_source",id);return json({ok:true,jobId})}
async function sourceDocuments(ctx:Awaited<ReturnType<typeof resolveDashboardContext>>,url:URL){const id=url.searchParams.get("id");if(!id)throw new DashboardError("id is required");await assertSource(ctx.tenantId,id);const docs=await rows("source_documents",{source_id:`eq.${id}`,tenant_id:`eq.${ctx.tenantId}`,select:"id,external_id,title,source_url,mime_type,byte_size,metadata,indexed_at",order:"indexed_at.desc",limit:"1000"});return json({items:docs})}

function normalizeConnectorInput(provider:string,input:Record<string,unknown>):Record<string,unknown>{const def=definition(provider);if(!def)throw new DashboardError("Unsupported connector");const out:Record<string,unknown>={};for(const f of def.fields){if(!(f.key in input))continue;let v=input[f.key];if((f.key==="capability_config"||f.key==="query_policy")&&typeof v==="string"&&v.trim()){try{v=JSON.parse(v)}catch{throw new DashboardError(`${f.label} must be valid JSON`)}}out[f.key]=v}return out}
async function listConnections(ctx:Awaited<ReturnType<typeof resolveDashboardContext>>){const existing=await rows("integrations",{tenant_id:`eq.${ctx.tenantId}`,select:"provider,credentials,active,created_at",limit:"100"});const health=await rows("integration_health",{tenant_id:`eq.${ctx.tenantId}`,select:"provider,status,message,checked_at,latency_ms",limit:"100"});const hm=new Map(health.map(h=>[String(h.provider),h]));const em=new Map(existing.map(e=>[String(e.provider),e]));const items=CONNECTORS.map(def=>{const e=em.get(def.id);return{...def,configured:Boolean(e),active:e?.active!==false,credentials:e?publicCredentialSummary(def.id,(e.credentials??{}) as Record<string,unknown>):{},health:hm.get(def.id)??null,oauthAvailable:oauthAvailable(def.id)}});return json({items})}
async function saveConnection(ctx:Awaited<ReturnType<typeof resolveDashboardContext>>,req:Request){requirePlanFeature(ctx.tenant,"liveIntegrations");requireDashboardRole(ctx,"admin");const b=await req.json().catch(()=>({})) as Record<string,unknown>;const provider=String(b.provider??"");const def=definition(provider);if(!def)throw new DashboardError("Unsupported connector");const incoming=normalizeConnectorInput(provider,(b.credentials??{}) as Record<string,unknown>);const existing=await rows("integrations",{tenant_id:`eq.${ctx.tenantId}`,provider:`eq.${provider}`,select:"id,credentials",limit:"1"});const merged=await encryptCredentials(provider,incoming,(existing[0]?.credentials??{}) as Record<string,unknown>);for(const f of def.fields.filter(x=>x.required)){if(!merged[f.key])throw new DashboardError(`${f.label} is required`)}if(existing[0])await write("PATCH",`integrations?id=eq.${existing[0].id}`,{credentials:merged,active:b.active!==false});else await write("POST","integrations",{tenant_id:ctx.tenantId,provider,credentials:merged,active:b.active!==false});const defaultActions=await ensureDefaultConnectorActions(ctx.tenantId,provider,ctx.user.id);await audit(ctx,"integration.updated","integration",provider,{provider,defaultActions});return json({ok:true,defaultActions})}
async function removeConnection(ctx:Awaited<ReturnType<typeof resolveDashboardContext>>,url:URL){requirePlanFeature(ctx.tenant,"liveIntegrations");requireDashboardRole(ctx,"admin");const provider=String(url.searchParams.get("provider")??"");if(!definition(provider))throw new DashboardError("Unsupported connector");const deps=await rows("data_sources",{tenant_id:`eq.${ctx.tenantId}`,connection_provider:`eq.${provider}`,select:"id",limit:"1"});if(deps[0])throw new DashboardError("Remove or reconfigure data sources using this connector first",409);const actionDeps=await rows("connector_actions",{tenant_id:`eq.${ctx.tenantId}`,provider:`eq.${provider}`,select:"id",limit:"1"});if(actionDeps[0])throw new DashboardError("Delete actions using this connector before disconnecting it",409);await write("DELETE",`integrations?tenant_id=eq.${ctx.tenantId}&provider=eq.${provider}`,{});await write("DELETE",`integration_health?tenant_id=eq.${ctx.tenantId}&provider=eq.${provider}`,{});await audit(ctx,"integration.deleted","integration",provider,{provider});return json({ok:true})}
async function testConnection(ctx:Awaited<ReturnType<typeof resolveDashboardContext>>,req:Request){requirePlanFeature(ctx.tenant,"liveIntegrations");requireDashboardRole(ctx,"admin");const b=await req.json().catch(()=>({})) as Record<string,unknown>;const provider=String(b.provider??"");if(!definition(provider))throw new DashboardError("Unsupported connector");const existing=await rows("integrations",{tenant_id:`eq.${ctx.tenantId}`,provider:`eq.${provider}`,select:"credentials",limit:"1"});if(!existing[0])throw new DashboardError("Connector is not configured",409);const start=Date.now();let result:{ok:boolean;message:string};try{result=await testConnector(provider,(existing[0].credentials??{}) as Record<string,unknown>)}catch(e){result={ok:false,message:e instanceof Error?e.message:"Connection test failed"}}const latency=Date.now()-start;const h=await rows("integration_health",{tenant_id:`eq.${ctx.tenantId}`,provider:`eq.${provider}`,select:"provider",limit:"1"});const status=result.ok?"healthy":"failed";if(h[0])await write("PATCH",`integration_health?tenant_id=eq.${ctx.tenantId}&provider=eq.${provider}`,{status,message:result.message,checked_at:new Date().toISOString(),latency_ms:latency});else await write("POST","integration_health",{tenant_id:ctx.tenantId,provider,status,message:result.message,checked_at:new Date().toISOString(),latency_ms:latency});await audit(ctx,"integration.tested","integration",provider,{status,latencyMs:latency});return json({ok:result.ok,status,message:result.message,latencyMs:latency},result.ok?200:422)}

async function listActions(ctx:Awaited<ReturnType<typeof resolveDashboardContext>>){const connected=await rows("integrations",{tenant_id:`eq.${ctx.tenantId}`,active:"eq.true",select:"provider",limit:"100"});await Promise.all(connected.map(x=>ensureDefaultConnectorActions(ctx.tenantId,String(x.provider)).catch(e=>console.warn("default actions seed failed",{provider:x.provider,error:e instanceof Error?e.message:String(e)}))));const items=await rows("connector_actions",{tenant_id:`eq.${ctx.tenantId}`,select:"*",order:"created_at.desc",limit:"500"});return json({items})}
async function saveAction(ctx:Awaited<ReturnType<typeof resolveDashboardContext>>,req:Request,url:URL){requirePlanFeature(ctx.tenant,"liveIntegrations");requireDashboardRole(ctx,"admin");const b=await req.json().catch(()=>({})) as Record<string,unknown>;const id=url.searchParams.get("id")||crypto.randomUUID();const provider=String(b.provider??"");if(!definition(provider))throw new DashboardError("Unsupported connector");const name=cleanName(b.name,80);if(!name)throw new DashboardError("Action name is required");const method=String(b.method??"GET").toUpperCase();if(!["GET","POST","PUT","PATCH","DELETE"].includes(method))throw new DashboardError("Invalid HTTP method");const path=String(b.pathTemplate??"").trim();if(!path.startsWith("/"))throw new DashboardError("Action path must begin with /");if(path.length>2000||path.includes("..")||path.includes("\\")||path.includes("//")||/%2e/i.test(path))throw new DashboardError("Action path is unsafe");const connected=await rows("integrations",{tenant_id:`eq.${ctx.tenantId}`,provider:`eq.${provider}`,active:"eq.true",select:"id",limit:"1"});if(!connected[0])throw new DashboardError("Connect this provider before creating an action",409);const schema=b.requestSchema&&typeof b.requestSchema==="object"&&!Array.isArray(b.requestSchema)?b.requestSchema:{};const mapping=b.responseMapping&&typeof b.responseMapping==="object"&&!Array.isArray(b.responseMapping)?b.responseMapping:{};const forcedConfirmation=method==="DELETE"||/refund|payment|delete|cancel/i.test(String(b.capability??"")+" "+name);const row={tenant_id:ctx.tenantId,provider,name,description:cleanName(b.description,500),capability:cleanName(b.capability,120)||"custom.read",method,path_template:path,request_schema:schema,response_mapping:mapping,require_confirmation:forcedConfirmation||b.requireConfirmation!==false,active:b.active!==false,updated_at:new Date().toISOString()};const existing=await rows("connector_actions",{id:`eq.${id}`,tenant_id:`eq.${ctx.tenantId}`,select:"id",limit:"1"});if(existing[0])await write("PATCH",`connector_actions?id=eq.${id}&tenant_id=eq.${ctx.tenantId}`,row);else await write("POST","connector_actions",{id,...row,created_by:ctx.user.id});await audit(ctx,"connector_action.updated","connector_action",id,{provider,name});return json({ok:true,id})}
async function deleteAction(ctx:Awaited<ReturnType<typeof resolveDashboardContext>>,url:URL){requirePlanFeature(ctx.tenant,"liveIntegrations");requireDashboardRole(ctx,"admin");const id=url.searchParams.get("id");if(!id)throw new DashboardError("id required");await write("DELETE",`connector_actions?id=eq.${id}&tenant_id=eq.${ctx.tenantId}`,{});await audit(ctx,"connector_action.deleted","connector_action",id);return json({ok:true})}

Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return handleOptions();try{const url=new URL(req.url);const tenantId=url.searchParams.get("tenantId")?.trim();if(!tenantId)throw new DashboardError("tenantId is required");const ctx=await resolveDashboardContext(req,tenantId);const action=url.searchParams.get("action")??"sources";if(action==="sources"){if(req.method==="GET")return listSources(ctx.tenantId,url);if(req.method==="POST")return createSource(ctx,req);if(req.method==="PUT")return updateSource(ctx,req,url);if(req.method==="DELETE")return deleteSource(ctx,url)}if(action==="sync"&&req.method==="POST")return syncNow(ctx,url);if(action==="documents"&&req.method==="GET")return sourceDocuments(ctx,url);if(action==="connections"){if(req.method==="GET")return listConnections(ctx);if(req.method==="PUT")return saveConnection(ctx,req);if(req.method==="DELETE")return removeConnection(ctx,url)}if(action==="connection_test"&&req.method==="POST")return testConnection(ctx,req);if(action==="actions"){if(req.method==="GET")return listActions(ctx);if(req.method==="PUT"||req.method==="POST")return saveAction(ctx,req,url);if(req.method==="DELETE")return deleteAction(ctx,url)}throw new DashboardError("Not found",404)}catch(e){const status=e instanceof DashboardError?e.status:500;console.error("data-sources",e);return json({error:e instanceof Error?e.message:"Internal error",code:e instanceof DashboardError?e.code:undefined},status)}});
