import React from "react";
import { createPlatformItem, deletePlatformItem, listPlatformItems, updatePlatformItem, type PlatformItem, type PlatformResource } from "../lib/api";
import { toast } from "../components/ui";

type Section = PlatformResource;
const META:Record<Section,{title:string;subtitle:string;add:string}>={
 procedures:{title:"Procedures",subtitle:"Reliable SOPs the agent follows step by step, with conditions, actions and approval points.",add:"New procedure"},
 widgets:{title:"Rich UI",subtitle:"Interactive interfaces the agent can render in chat: products, carts, forms, bookings, status and custom cards.",add:"New widget"},
 contacts:{title:"Contacts",subtitle:"Unified customer identity across chat, email, voice and messaging channels.",add:"New contact"},
 inbox:{title:"Helpdesk",subtitle:"One human + AI inbox for escalations and customer conversations across every channel.",add:"New thread"},
 tests:{title:"Testing",subtitle:"Save common and edge-case scenarios so changes can be regression tested before release.",add:"New scenario"},
 insights:{title:"Analytics",subtitle:"Topics, sentiment, resolution and evidence from customer conversations.",add:"Add insight"},
 suggestions:{title:"Backstage",subtitle:"Evidence-backed improvement proposals. Nothing changes until a human approves it.",add:"New suggestion"},
 channels:{title:"Channels",subtitle:"Deploy the same agent across chat, email, WhatsApp, voice, Slack and social messaging.",add:"Add channel"},
};
const TEMPLATES:Partial<Record<Section,Array<Record<string,unknown>>>>={
 procedures:[
  {name:"Order return & refund",description:"Verify the customer, retrieve the order, check policy eligibility, offer exchange where appropriate, request approval for restricted refunds, then confirm the outcome.",trigger_phrases:["return","refund","wrong size"],status:"draft",steps:[{type:"ask",text:"Request order number or verified email",required:true},{type:"action",action:"lookup_order",required:true},{type:"condition",if:"eligible_return_window",then:"continue",else:"escalate"},{type:"approval",text:"Require approval when refund exceeds tenant limit"},{type:"action",action:"create_refund"}]},
  {name:"Identity verification",description:"Verify identity before exposing private account information.",trigger_phrases:["my account","my invoice","my order"],status:"draft",steps:[{type:"verify_identity",required:true},{type:"condition",if:"verified",then:"continue",else:"escalate"}]},
  {name:"Support escalation",description:"Escalate urgent, frustrated or unresolved customers with context preserved.",trigger_phrases:["human","complaint","urgent"],status:"draft",steps:[{type:"summarize"},{type:"action",action:"create_ticket"},{type:"handoff",required:true}]}
 ],
 widgets:[
  {name:"Product gallery",kind:"product_gallery",description:"Product image, live price, variants, stock and deterministic cart controls.",action_name:"search_products",active:true,schema:{state:["selectedVariant","quantity"]}},
  {name:"Booking picker",kind:"slot_picker",description:"Date and time selection with confirmation and live availability.",action_name:"get_available_slots",active:true,schema:{state:["date","slot"]}},
  {name:"Order status",kind:"status_card",description:"Live order and delivery status with customer-safe actions.",action_name:"track_order",active:true,schema:{}},
  {name:"Smart form",kind:"form",description:"Validated multi-field data collection without turning every field into a chat message.",active:true,schema:{}}
 ],
 channels:[
  {channel:"email",display_name:"Support Email",status:"disconnected",config:{mode:"inbound_outbound"}},
  {channel:"voice",display_name:"Voice / Telephone",status:"disconnected",config:{provider:"twilio",mode:"inbound_outbound"}},
  {channel:"whatsapp",display_name:"WhatsApp",status:"disconnected",config:{commerce:true}},
  {channel:"slack",display_name:"Slack",status:"disconnected",config:{}},
  {channel:"instagram",display_name:"Instagram",status:"disconnected",config:{}},
  {channel:"messenger",display_name:"Messenger",status:"disconnected",config:{}}
 ]
};
function text(v:unknown){if(Array.isArray(v))return v.join(", ");if(v&&typeof v==="object")return JSON.stringify(v);return String(v??"")}
export default function AgentPlatform({tenantId,section}:{tenantId:string;section:Section}){
 const [items,setItems]=React.useState<PlatformItem[]>([]),[loading,setLoading]=React.useState(true),[editing,setEditing]=React.useState<PlatformItem|null>(null),[show,setShow]=React.useState(false);const [summary,setSummary]=React.useState<Record<string,unknown>>({});
 const load=React.useCallback(()=>{setLoading(true);listPlatformItems(tenantId,section).then(r=>{setItems(r.items);setSummary(r.summary||{})}).catch(e=>toast(e instanceof Error?e.message:"Could not load" ,"error")).finally(()=>setLoading(false))},[tenantId,section]);React.useEffect(load,[load]);
 const seed=async(t:Record<string,unknown>)=>{try{await createPlatformItem(tenantId,section,t);toast("Created","success");load()}catch(e){toast(e instanceof Error?e.message:"Could not create","error")}};
 const remove=async(id:string)=>{if(!confirm("Delete this item?"))return;await deletePlatformItem(tenantId,section,id);load()};
 const meta=META[section];
 return <div className="page"><div className="page-header"><div><h1>{meta.title}</h1><p className="sub">{meta.subtitle}</p></div>{section!=="insights"&&<button className="btn primary" onClick={()=>{setEditing(null);setShow(true)}}>{meta.add}</button>}</div>
 {section==="insights"&&<div className="stats-grid" style={{marginBottom:18}}><div className="stat"><div className="stat-label">Analysed</div><div className="stat-value">{text(summary.total||0)}</div></div><div className="stat"><div className="stat-label">Sentiment</div><div className="stat-value" style={{fontSize:15}}>{text(summary.sentiment||{})}</div></div><div className="stat"><div className="stat-label">Top topics</div><div className="stat-value" style={{fontSize:15}}>{text(summary.topics||[])}</div></div></div>}
 {TEMPLATES[section]&&items.length===0&&<div className="card" style={{marginBottom:18}}><h3>Start from a production template</h3><p className="muted">Templates are created as drafts/disconnected items so nothing goes live without review.</p><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{TEMPLATES[section]!.map((t,i)=><button key={i} className="btn secondary" onClick={()=>seed(t)}>{String(t.name||t.display_name)}</button>)}</div></div>}
 <div className="card">{loading?<p className="muted">Loading…</p>:items.length===0?<div className="empty"><h3>No {meta.title.toLowerCase()} yet</h3><p className="muted">Create one when you're ready.</p></div>:<div className="table-wrap"><table><thead><tr><th>Name</th><th>Status / type</th><th>Details</th><th></th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><strong>{text(x.name||x.display_name||x.subject||x.topic||x.title||x.email||"Untitled")}</strong></td><td>{text(x.status||x.kind||x.channel||x.sentiment||"")}</td><td className="muted">{text(x.description||x.rationale||x.email||x.input||x.ai_summary||x.resolution||"").slice(0,180)}</td><td><div style={{display:"flex",gap:6}}><button className="btn ghost" onClick={()=>{setEditing(x);setShow(true)}}>Edit</button>{section!=="insights"&&<button className="btn ghost" onClick={()=>remove(x.id)}>Delete</button>}</div></td></tr>)}</tbody></table></div>}</div>
 {show&&<Editor section={section} item={editing} onClose={()=>setShow(false)} onSave={async body=>{try{if(editing)await updatePlatformItem(tenantId,section,editing.id,body);else await createPlatformItem(tenantId,section,body);setShow(false);toast("Saved","success");load()}catch(e){toast(e instanceof Error?e.message:"Could not save","error")}}}/>}</div>
}
function Editor({section,item,onClose,onSave}:{section:Section;item:PlatformItem|null;onClose:()=>void;onSave:(b:Record<string,unknown>)=>Promise<void>}){const [name,setName]=React.useState(text(item?.name||item?.display_name||item?.title||item?.email||""));const [details,setDetails]=React.useState(text(item?.description||item?.rationale||item?.input||item?.subject||""));const [extra,setExtra]=React.useState(section==="procedures"?JSON.stringify(item?.steps||[],null,2):section==="widgets"?JSON.stringify(item?.schema||{},null,2):"");const [saving,setSaving]=React.useState(false);const submit=async()=>{setSaving(true);let body:Record<string,unknown>={};try{if(section==="procedures")body={name,description:details,status:item?.status||"draft",steps:extra?JSON.parse(extra):[]};else if(section==="widgets")body={name,description:details,kind:item?.kind||"custom",active:item?.active??true,schema:extra?JSON.parse(extra):{}};else if(section==="contacts")body={name,email:details};else if(section==="inbox")body={subject:name,status:item?.status||"open",priority:item?.priority||"normal",ai_summary:details,channel:item?.channel||"chat"};else if(section==="tests")body={name,input:details,active:true};else if(section==="suggestions")body={title:name,rationale:details,kind:item?.kind||"improvement",status:item?.status||"pending"};else if(section==="channels")body={display_name:name,channel:details||item?.channel||"custom",status:item?.status||"disconnected",config:item?.config||{}};await onSave(body)}catch(e){toast(e instanceof Error?e.message:"Invalid form","error")}finally{setSaving(false)}};return <div className="modal-overlay" onClick={onClose}><div className="modal" onClick={e=>e.stopPropagation()}><h2>{item?"Edit":"Create"} {META[section].title}</h2><label className="field-label">{section==="contacts"?"Name":"Name / title"}</label><input className="input" value={name} onChange={e=>setName(e.target.value)}/><label className="field-label" style={{marginTop:12}}>{section==="contacts"?"Email":section==="channels"?"Channel key":"Description / input"}</label><textarea className="input" rows={4} value={details} onChange={e=>setDetails(e.target.value)}/>{(section==="procedures"||section==="widgets")&&<><label className="field-label" style={{marginTop:12}}>Structured definition (JSON)</label><textarea className="input mono" rows={9} value={extra} onChange={e=>setExtra(e.target.value)}/></>}<div style={{display:"flex",justifyContent:"flex-end",gap:8,marginTop:16}}><button className="btn ghost" onClick={onClose}>Cancel</button><button className="btn primary" disabled={saving||!name.trim()} onClick={submit}>{saving?"Saving…":"Save"}</button></div></div></div>}
