import React from "react";
import { getTeam, inviteTeamMember, removeTeamMember, updateTeamRole, type TeamItem, type PlanEntitlements } from "../lib/api";

export default function TeamPage({tenantId,entitlements}:{tenantId:string;entitlements:PlanEntitlements|null}){
 const [items,setItems]=React.useState<TeamItem[]>([]); const [error,setError]=React.useState(""); const[email,setEmail]=React.useState(""); const[inviteRole,setInviteRole]=React.useState<TeamItem["role"]>("viewer");
 const advanced = entitlements?.advancedPermissions === true;
 const roles: TeamItem["role"][] = advanced ? ["viewer","agent","admin","owner"] : ["viewer","agent"];
 const load=React.useCallback(()=>getTeam(tenantId).then(r=>setItems(r.items)).catch(e=>setError(e.message)),[tenantId]); React.useEffect(()=>{load()},[load]);
 React.useEffect(()=>{ if(!roles.includes(inviteRole)) setInviteRole("viewer"); },[advanced]);
 return <div className="page">
   <div className="page-head"><div><h1>Team & access</h1><p className="desc">Invite teammates and control what each person can manage.</p></div></div>
   {error&&<div className="err">{error}</div>}
   {!advanced&&<div className="info-banner plan-banner"><div className="info-banner-icon">i</div><div><strong>Growth permissions</strong><p>You can add viewers and agents. Upgrade to Scale to assign admin or owner roles.</p></div></div>}
   <div className="card section-card"><div className="section-head"><div><h2>Invite member</h2><p>Send access to a teammate by email.</p></div></div><div className="team-invite-row"><input className="input" type="email" placeholder="name@company.com" value={email} onChange={e=>setEmail(e.target.value)}/><select value={inviteRole} onChange={e=>setInviteRole(e.target.value as TeamItem["role"])}>{roles.map(role=><option key={role}>{role}</option>)}</select><button className="btn primary" disabled={!email.trim()} onClick={async()=>{try{setError("");await inviteTeamMember(tenantId,email,inviteRole);setEmail("");await load()}catch(e){setError(e instanceof Error?e.message:"Invite failed")}}}>Invite member</button></div></div>
   <div className="card table-card"><div className="section-head table-section-head"><div><h2>Workspace members</h2><p>{items.length} {items.length===1?"member":"members"} with access.</p></div></div>{items.length===0?<div className="empty-state compact"><div className="empty-state-icon">＋</div><h3>No members yet</h3><p>Invite your first teammate above.</p></div>:<table><thead><tr><th>User</th><th>Role</th><th>Added</th><th className="table-action-head">Actions</th></tr></thead><tbody>{items.map(m=>{const roleLocked=!advanced&&(m.role==="owner"||m.role==="admin");return <tr key={m.id}><td><code className="code-id">{m.user_id}</code></td><td>{roleLocked?<span className="role-display">{m.role} <small className="muted">Scale role</small></span>:<select className="table-select" value={m.role} onChange={async e=>{try{setError("");await updateTeamRole(tenantId,m.id,e.target.value as TeamItem["role"]);load()}catch(err){setError(err instanceof Error?err.message:"Role update failed")}}}>{roles.map(role=><option key={role}>{role}</option>)}</select>}</td><td className="muted table-nowrap">{new Date(m.created_at).toLocaleString()}</td><td className="table-action-cell"><button className="btn ghost sm danger-soft" onClick={async()=>{if(confirm("Remove this member?")){try{setError("");await removeTeamMember(tenantId,m.id);load()}catch(err){setError(err instanceof Error?err.message:"Remove failed")}}}}>Remove</button></td></tr>})}</tbody></table>}</div>
 </div>
}
