import React from "react";
import { getTeam, inviteTeamMember, removeTeamMember, updateTeamRole, type TeamItem } from "../lib/api";
export default function TeamPage({tenantId}:{tenantId:string}){
 const [items,setItems]=React.useState<TeamItem[]>([]); const [error,setError]=React.useState(""); const[email,setEmail]=React.useState(""); const[inviteRole,setInviteRole]=React.useState<TeamItem["role"]>("viewer");
 const load=React.useCallback(()=>getTeam(tenantId).then(r=>setItems(r.items)).catch(e=>setError(e.message)),[tenantId]); React.useEffect(()=>{load()},[load]);
 return <div className="page"><h1>Team & access</h1><p className="desc">Tenant-scoped roles. Owners can invite users and manage access; the last owner cannot be removed or demoted.</p>{error&&<div className="err">{error}</div>}
 <div className="card" style={{marginBottom:16}}><h2>Invite member</h2><div style={{display:"flex",gap:8}}><input className="input" type="email" placeholder="name@company.com" value={email} onChange={e=>setEmail(e.target.value)}/><select value={inviteRole} onChange={e=>setInviteRole(e.target.value as TeamItem["role"])}><option>viewer</option><option>agent</option><option>admin</option><option>owner</option></select><button className="btn primary" onClick={async()=>{try{await inviteTeamMember(tenantId,email,inviteRole);setEmail("");await load()}catch(e){setError(e instanceof Error?e.message:"Invite failed")}}}>Invite</button></div></div>
 <div className="card"><table style={{width:"100%"}}><thead><tr><th>User ID</th><th>Role</th><th>Added</th><th></th></tr></thead><tbody>{items.map(m=><tr key={m.id}><td><code>{m.user_id}</code></td><td><select value={m.role} onChange={async e=>{await updateTeamRole(tenantId,m.id,e.target.value as TeamItem["role"]);load()}}><option>owner</option><option>admin</option><option>agent</option><option>viewer</option></select></td><td>{new Date(m.created_at).toLocaleString()}</td><td><button className="btn ghost" onClick={async()=>{if(confirm("Remove this member?")){await removeTeamMember(tenantId,m.id);load()}}}>Remove</button></td></tr>)}</tbody></table></div></div>
}
