import React from "react";
import { getTeam, inviteTeamMember, removeTeamMember, updateTeamRole, type TeamItem, type PlanEntitlements } from "../lib/api";

export default function TeamPage({tenantId,entitlements}:{tenantId:string;entitlements:PlanEntitlements|null}){
 const [items,setItems]=React.useState<TeamItem[]>([]); const [error,setError]=React.useState(""); const[email,setEmail]=React.useState(""); const[inviteRole,setInviteRole]=React.useState<TeamItem["role"]>("viewer");
 const advanced = entitlements?.advancedPermissions === true;
 const roles: TeamItem["role"][] = advanced ? ["viewer","agent","admin","owner"] : ["viewer","agent"];
 const load=React.useCallback(()=>getTeam(tenantId).then(r=>setItems(r.items)).catch(e=>setError(e.message)),[tenantId]); React.useEffect(()=>{load()},[load]);
 React.useEffect(()=>{ if(!roles.includes(inviteRole)) setInviteRole("viewer"); },[advanced]);
 return <div className="page"><h1>Team & access</h1><p className="desc">Growth includes team access with viewer and agent roles. Scale unlocks advanced admin and owner permissions.</p>{error&&<div className="err">{error}</div>}
 {!advanced&&<div className="card" style={{marginBottom:16}}><b>Growth permissions</b><p className="muted" style={{marginBottom:0}}>You can add viewers and agents. Upgrade to Scale to assign admin or owner roles.</p></div>}
 <div className="card" style={{marginBottom:16}}><h2>Invite member</h2><div style={{display:"flex",gap:8}}><input className="input" type="email" placeholder="name@company.com" value={email} onChange={e=>setEmail(e.target.value)}/><select value={inviteRole} onChange={e=>setInviteRole(e.target.value as TeamItem["role"])}>{roles.map(role=><option key={role}>{role}</option>)}</select><button className="btn primary" onClick={async()=>{try{setError("");await inviteTeamMember(tenantId,email,inviteRole);setEmail("");await load()}catch(e){setError(e instanceof Error?e.message:"Invite failed")}}}>Invite</button></div></div>
 <div className="card"><table style={{width:"100%"}}><thead><tr><th>User ID</th><th>Role</th><th>Added</th><th></th></tr></thead><tbody>{items.map(m=>{const roleLocked=!advanced&&(m.role==="owner"||m.role==="admin");return <tr key={m.id}><td><code>{m.user_id}</code></td><td>{roleLocked?<span>{m.role} <small className="muted">(Scale role)</small></span>:<select value={m.role} onChange={async e=>{try{setError("");await updateTeamRole(tenantId,m.id,e.target.value as TeamItem["role"]);load()}catch(err){setError(err instanceof Error?err.message:"Role update failed")}}}>{roles.map(role=><option key={role}>{role}</option>)}</select>}</td><td>{new Date(m.created_at).toLocaleString()}</td><td><button className="btn ghost" onClick={async()=>{if(confirm("Remove this member?")){try{setError("");await removeTeamMember(tenantId,m.id);load()}catch(err){setError(err instanceof Error?err.message:"Remove failed")}}}}>Remove</button></td></tr>})}</tbody></table></div></div>
}
