// Build supabase/functions/widget/index.ts from the built widget bundle.
// Run: bun run build:widget && bun scripts/build-widget-function.ts
// The function serves dist/widget.js as a static asset at /functions/v1/widget.js
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const src = join(root, "widget", "dist", "widget.js");
const outDir = join(root, "supabase", "functions", "widget");
const out = join(outDir, "index.ts");

let js = readFileSync(src, "utf8");
// Escape so the bundle survives embedding as a template literal.
js = js.replaceAll("\\", "\\\\").replaceAll("`", "\\`").replaceAll("${", "\\${");

mkdirSync(outDir, { recursive: true });
writeFileSync(
  out,
  `// Generated by scripts/build-widget-function.ts — do not edit by hand.
// Run \`bun run build:widget && bun scripts/build-widget-function.ts\` to refresh.
const WIDGET_JS = \`${js}\`;

Deno.serve((req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response(null, {
      headers: {
        "access-control-allow-origin": "*",
        "access-control-allow-methods": "GET, OPTIONS",
        "access-control-allow-headers": "content-type",
      },
    });
  }
  return new Response(WIDGET_JS, {
    headers: {
      "content-type": "application/javascript; charset=utf-8",
      "cache-control": "public, max-age=3600",
      "access-control-allow-origin": "*",
    },
  });
});
`,
  "utf8",
);
console.log(`Wrote ${out} (${js.length.toLocaleString()} chars of JS embedded)`);
